export { default as AcceptacioPropTypes } from "./acceptacio.prop-types";
export { default as AcceptacionsSociPropTypes } from "./acceptacions-soci.prop-types";
export { default as AssaigPropTypes } from "./assaig.prop-types";
export { default as FormacioPropTypes } from "./formacio.prop-types";
export { default as IdPropTypes } from "./id.prop-types";
export { default as SociPropTypes } from "./soci.prop-types";
export { default as MovimentPropTypes } from "./moviment.prop-types";
export { default as ProjectePropTypes } from "./projecte.prop-types";
export { default as EsdevenimentPropTypes } from "./esdeveniment.prop-types";
