openapi: 3.0.1
info:
  title: Associació Musical Catalana Crescendo
  version: 0.2.0
  description: Documentació de l’API per a l’Associació Musical Catalana Crescendo
  contact:
    name: Albert Mañosa
    email: albertmasa2@gmail.com
servers:
  - url: "/api"
consumes:
  - application/json
produces:
  - application/json

paths:
  /agrupacions:
    get:
      summary: Llista d’agrupacions
      tags: [Agrupacions]
      security:
        - JWT: []
      responses:
        "200":
          description: Obtén la llista d’agrupacions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Agrupacio"
        "401":
          description: Sense autorització
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /agrupacions/avisos/{name}:
    get:
      summary: Informació d’un avís
      tags: [Agrupacions]
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: Nom de l’avís
      responses:
        "200":
          description: Obtén la informació de l’avís
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Avis"

  /agrupacions/cursos:
    get:
      summary: Llista de cursos
      tags: [Agrupacions]
      security:
        - JWT: []
      responses:
        "200":
          description: Obtén la llista de cursos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Curs"

components:
  schemas:
    Acceptacio:
      type: object
      properties:
        titol:
          type: string
        form_name:
          type: string
        requerida:
          type: boolean
        descripcio:
          type: string

    Agrupacio:
      type: object
      properties:
        id_agrupacio:
          type: integer
        nom:
          type: string
        nif:
          type: string
        id_tipus_agrupacio:
          type: integer
        tipus_agrupacio:
          type: string

    Avis:
      type: object
      properties:
        titol:
          type: string
        descripcio:
          type: string
          nullable: true
        titol_acceptacions:
          type: string
        requerit:
          type: boolean
        data_inici:
          type: string
          format: date
          nullable: true
        data_final:
          type: string
          format: date
          nullable: true
        seccions:
          type: array
          items:
            $ref: "#/components/schemas/Seccio"
        acceptacions:
          type: array
          items:
            $ref: "#/components/schemas/Acceptacio"

    Curs:
      type: object
      properties:
        id_curs:
          type: string
          pattern: '^\d{2}-\d{2}$'
        inici:
          type: string
          format: date
        final:
          type: string
          format: date

    Error:
      type: object
      properties:
        error:
          type: object
          properties:
            status:
              type: integer
            message:
              type: string

    Seccio:
      type: object
      properties:
        id_seccio_avis:
          type: integer
        titol:
          type: string
        descripcio:
          type: string

  securitySchemes:
    JWT:
      type: apiKey
      name: JWT
      in: header
