openapi: 3.0.3
info:
  title: Associació Musical Catalana Crescendo
  version: 0.3.1
  description: Documentació de l’API per a l’Associació Musical Catalana Crescendo
  contact:
    name: Albert Mañosa
    email: albertmasa2@gmail.com
servers:
  - url: /api

tags:
  - name: Assajos
  - name: Auth
  - name: Concerts
  - name: Entitats
  - name: Esdeveniments
  - name: Establiments
  - name: Formacions
  - name: Localitzacions
  - name: Moviments
  - name: Obres
  - name: Projectes
  - name: Socis
  - name: Titulars
  - name: Usuaris

paths:
  /entitats:
    get:
      summary: Obtén la llista d’entitats
      tags: [ Entitats ]
      security:
        - JWT: [ ]
      responses:
        200:
          description: Llista d’entitats
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Entitat"
        401:
          $ref: "#/components/responses/Unauthorized"

  /entitats/avisos/{name}:
    get:
      summary: Obtén la informació d’un avís
      tags: [ Entitats ]
      parameters:
        - $ref: "#/components/parameters/name"
      responses:
        200:
          description: Informació de l’avís
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Avis"

  /entitats/cursos:
    get:
      summary: Obtén la llista de cursos
      tags: [ Entitats ]
      security:
        - JWT: [ ]
      responses:
        200:
          description: Llista de cursos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Curs"
        401:
          $ref: "#/components/responses/Unauthorized"

  /assajos:
    post:
      tags: [ Assajos ]
      security:
        - JWT: [ ]
      summary: Afegeix un assaig
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                assaig:
                  $ref: "#/components/schemas/AssaigPost"
      responses:
        204:
          $ref: "#/components/responses/Posted"
        401:
          $ref: "#/components/responses/Unauthorized"

  /assajos/count:
    get:
      tags: [ Assajos ]
      security:
        - JWT: [ ]
      summary: Obtén el recompte d’assajos
      responses:
        200:
          description: Recompte d’assajos
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Count"
        401:
          $ref: "#/components/responses/Unauthorized"

  /assajos/historial:
    get:
      tags: [ Assajos ]
      security:
        - JWT: [ ]
      summary: Obtén l’historial d’assajos
      responses:
        200:
          description: Historial d’assajos
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Historial"
        401:
          $ref: "#/components/responses/Unauthorized"

  /assajos/assistencia:
    get:
      tags: [ Assajos ]
      security:
        - JWT: [ ]
      summary: Obtén l’assistència d’assajos
      parameters:
        - in: query
          name: group-by
          schema:
            type: string
            enum: [ estat, veus ]
          description: Agrupació de les dades
      responses:
        200:
          description: Assistència als assajos
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/AssistenciaAssajosEstat"
                  - $ref: "#/components/schemas/AssistenciaAssajosVeus"
        401:
          $ref: "#/components/responses/Unauthorized"

  /assajos/{id}:
    get:
      tags: [ Assajos ]
      security:
        - JWT: [ ]
      summary: Obtén la informació d’un assaig
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        200:
          description: Informació de l’assaig
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AssaigComplet"
        401:
          $ref: "#/components/responses/Unauthorized"

    delete:
      tags: [ Assajos ]
      security:
        - JWT: [ ]
      summary: Elimina un assaig
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        204:
          $ref: "#/components/responses/Deleted"
        401:
          $ref: "#/components/responses/Unauthorized"

  /assajos/{id}/moviments:
    get:
      tags: [ Assajos ]
      security:
        - JWT: [ ]
      summary: Obtén els moviments d’un assaig
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        200:
          description: Moviments de l’assaig
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Moviment"
        401:
          $ref: "#/components/responses/Unauthorized"

    post:
      tags: [ Assajos ]
      security:
        - JWT: [ ]
      summary: Afegeix un moviment a un assaig
      parameters:
        - $ref: "#/components/parameters/id"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: integer
      responses:
        204:
          $ref: "#/components/responses/Posted"
        401:
          $ref: "#/components/responses/Unauthorized"

  /assajos/{id_assaig}/moviments/{id_moviment}:
    delete:
      tags: [ Assajos ]
      security:
        - JWT: [ ]
      summary: Elimina un moviment d’un assaig
      parameters:
        - in: path
          name: id_assaig
          description: Identificador de l’assaig
          schema:
            type: integer
        - in: path
          name: id_moviment
          description: Identificador del moviment
          schema:
            type: integer
      responses:
        204:
          $ref: "#/components/responses/Deleted"
        401:
          $ref: "#/components/responses/Unauthorized"

  /assajos/{id}/projectes:
    get:
      tags: [ Assajos ]
      security:
        - JWT: [ ]
      summary: Obtén els projectes d’un assaig
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        200:
          description: Projectes de l’assaig
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Projecte"
        401:
          $ref: "#/components/responses/Unauthorized"

    post:
      tags: [ Assajos ]
      security:
        - JWT: [ ]
      summary: Afegeix un projecte a un assaig
      parameters:
        - $ref: "#/components/parameters/id"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: integer
      responses:
        204:
          $ref: "#/components/responses/Posted"
        401:
          $ref: "#/components/responses/Unauthorized"

  /assajos/{id_assaig}/projectes/{id_projecte}:
    delete:
      tags: [ Assajos ]
      security:
        - JWT: [ ]
      summary: Elimina un projecte d’un assaig
      parameters:
        - in: path
          name: id_assaig
          description: Identificador de l’assaig
          schema:
            type: integer
        - in: path
          name: id_moviment
          description: Identificador del moviment
          schema:
            type: integer
      responses:
        204:
          $ref: "#/components/responses/Deleted"
        401:
          $ref: "#/components/responses/Unauthorized"

  /auth/sign-in:
    post:
      tags: [ Auth ]
      summary: Inicia la sessió
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  $ref: "#/components/schemas/Usuari"
      responses:
        200:
          description: Informació de l’usuari
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: "#/components/schemas/Usuari"
                  accessToken:
                    type: string

        403:
          $ref: "#/components/responses/Forbidden"

components:
  responses:
    Deleted:
      description: Recurs eliminat satisfactòriament

    Forbidden:
      description: Sense permís
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

    Posted:
      description: Recurs afegit satisfactòriament

    Unauthorized:
      description: Sense autorització
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  parameters:
    name:
      in: path
      name: name
      schema:
        type: string
      required: true
      description: Nom del recurs

    id:
      in: path
      name: id
      schema:
        type: integer
      required: true
      description: Identificador del recurs

  schemas:
    Acceptacio:
      type: object
      properties:
        titol:
          type: string
        form_name:
          type: string
        requerida:
          type: boolean
        descripcio:
          type: string

    Entitat:
      type: object
      properties:
        id_entitat:
          type: integer
        nom:
          type: string
        nif:
          type: string
        id_tipus_entitat:
          type: integer
        tipus_entitat:
          type: string

    Assaig:
      allOf:
        - $ref: "#/components/schemas/Esdeveniment"
        - type: object
          properties:
            id_assaig:
              type: integer
              readOnly: true
            titol:
              type: string
              readOnly: true
            es_general:
              type: boolean
            es_extra:
              type: boolean
            es_parcial:
              type: boolean
              readOnly: true

    AssaigPost:
      allOf:
        - $ref: "#/components/schemas/Assaig"
        - type: object
          properties:
            hora:
              type: array
              writeOnly: true
              items:
                type: string
                format: time
              minItems: 2
              maxItems: 2
            formacions:
              type: array
              writeOnly: true
              items:
                type: integer
            projectes:
              type: array
              writeOnly: true
              items:
                type: integer

    AssaigComplet:
      allOf:
        - $ref: "#/components/schemas/Assaig"
        - type: object
          properties:
            formacions:
              type: array
              readOnly: true
              items:
                $ref: "#/components/schemas/Formacio"
            projectes:
              type: array
              readOnly: true
              items:
                $ref: "#/components/schemas/Projecte"

    Assistencia:
      type: object
      properties:
        data_inici:
          type: string
          format: date
        hora_inici:
          type: string
          format: time
        convocats:
          type: integer

    AssistenciaAssajos:
      allOf:
        - $ref: "#/components/schemas/Assistencia"
        - type: object
          properties:
            id_assaig:
              type: integer

    AssistenciaAssajosEstat:
      allOf:
        - $ref: "#/components/schemas/AssistenciaAssajos"
        - type: object
          properties:
            confirmats_retard:
              type: integer
            confirmats_puntuals:
              type: integer
            pendents:
              type: integer
            cancelats:
              type: integers

    AssistenciaAssajosVeus:
      allOf:
        - $ref: "#/components/schemas/AssistenciaAssajos"
        - type: object
          properties:
            sopranos:
              type: integer
            contralts:
              type: integer
            tenors:
              type: integer
            baixos:
              type: integers

    Avis:
      type: object
      properties:
        titol:
          type: string
        descripcio:
          type: string
          nullable: true
        titol_acceptacions:
          type: string
        requerit:
          type: boolean
        data_inici:
          type: string
          format: date
          nullable: true
        data_final:
          type: string
          format: date
          nullable: true
        seccions:
          type: array
          items:
            $ref: "#/components/schemas/Seccio"
        acceptacions:
          type: array
          items:
            $ref: "#/components/schemas/Acceptacio"

    Count:
      type: integer

    Curs:
      type: object
      properties:
        id_curs:
          type: string
          pattern: '^\d{2}-\d{2}$'
        inici:
          type: string
          format: date
        final:
          type: string
          format: date

    Error:
      type: object
      properties:
        error:
          type: object
          properties:
            status:
              type: integer
            message:
              type: string

    Esdeveniment:
      type: object
      properties:
        id_esdeveniment:
          type: integer
          readOnly: true
        data:
          type: string
          format: date
        datahora_inici:
          type: string
          format: date-time
          readOnly: true
        hora_inici:
          type: string
          format: time
          readOnly: true
        datahora_final:
          type: string
          format: date-time
          readOnly: true
        hora_final:
          type: string
          format: time
          readOnly: true
        nom_localitzacio:
          type: string
          readOnly: true
        nom_establiment:
          type: string
          readOnly: true
        id_esdeveniment_ajornat:
          type: integer
          readOnly: true
        id_estat_esdeveniment:
          type: integer
        estat_esdeveniment:
          type: string
          readOnly: true
        id_estat_localitzacio:
          type: integer
          readOnly: true
        estat_localitzacio:
          type: string
          readOnly: true

    Formacio:
      type: object
      properties:
        id_formacio:
          type: integer
        nom:
          type: string
        nom_curs:
          type: string
          nullable: true

    Historial:
      type: array
      items:
        type: object
        properties:
          x:
            type: string
          y:
            type: integer

    Moviment:
      type: object
      properties:
        id_moviment:
          type: integer
        id_obra:
          type: integer
        num_cataleg:
          type: string
        ordre:
          type: integer
        es_unic_moviment:
          type: boolean
        durada:
          type: string
          format: time
        titol_moviment:
          type: string
        titol_obra:
          type: string
        any_inici:
          type: integer
        projectes:
          type: array
          items:
            $ref: "#/components/schemas/Projecte"
        id_esdeveniment_musical:
          type: integer

    Projecte:
      type: object
      properties:
        id_projecte:
          type: integer
        titol:
          type: string
        inicials:
          type: string
          pattern: "^[A-Z]{1,3}$"
        color:
          type: string
          pattern: "^(?:[0-9a-fA-F]{3}){1,2}$"

    Seccio:
      type: object
      properties:
        id_seccio_avis:
          type: integer
        titol:
          type: string
        descripcio:
          type: string

    Usuari:
      type: object
      properties:
        id_usuari:
          type: integer
          readOnly: true
        username:
          type: string
        password:
          type: string
          format: password
          writeOnly: true
        nom:
          type: string
          readOnly: true
        cognoms:
          type: string
          readOnly: true
        es_dona:
          type: boolean
          readOnly: true
        id_persona:
          type: integer
          readOnly: true
        avisos:
          type: array
          readOnly: true
          items:
            type: integer
        roles:
          type: array
          readOnly: true
          items:
            type: string
            enum:
              - user
              - board_of_directors
              - musical_management
              - admin

  securitySchemes:
    JWT:
      type: apiKey
      in: header
      name: Authorization
      bearerFormat: JWT
