export const SIGNIN_USER_SUCCESS = "SIGNIN_USER_SUCCESS";
export const SIGNIN_USER_FAILURE = "SIGNIN_USER_FAILURE";
export const VALIDATED_IN_WAITING_LIST = "VALIDATED_IN_WAITING_LIST";
export const REMOVE_ACCEPTANCE_NOTICE = "REMOVE_ACCEPTANCE_NOTICE";
export const LOGOUT_USER = "LOGOUT_USER";
